database:
  type: mysql

  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: skyblock

  worker-limit: 2

common:
  items:
    - name: "Diamond"
      id: 264
      meta: 0
      chance: 50
      amount: 10
    - name: "Say Hi"
      id: 339
      meta: 0
      chance: 50
      amount: 1
      cmd: "say Hi"
    - id: 277
      meta: 0
      chance: 50
      amount: 10

rare:
  items:
    - name: "Diamond"
      id: 264
      meta: 0
      chance: 50
      amount: 10
    - name: "Say Hi"
      id: 339
      meta: 0
      chance: 50
      amount: 1
      cmd: "say hi"

epic:
  items:
    - name: "Diamond"
      id: 264
      meta: 0
      chance: 50
      amount: 10
    - name: "Say Hi"
      id: 339
      meta: 0
      chance: 50
      amount: 1
      cmd: "say hi"

legendary:
  items:
    - name: "Diamond"
      id: 264
      meta: 0
      chance: 50
      amount: 10
    - name: "Say Hi"
      id: 339
      meta: 0
      chance: 50
      amount: 1
      cmd: "say Hi"
    - id: 277
      meta: 0
      chance: 50
      amount: 10