name: CustomPotions
version: 1.0.0
api: 3.0.0
main: CustomPotions\Main
author: diverse
description: Custom Potions For Versai Factions.

commands:
  custompotion:
    description: "Give a player custom potions!"