package pallete

import (
	"github.com/df-mc/dragonfly/server/block"
	"github.com/df-mc/dragonfly/server/block/cube"
	"github.com/df-mc/dragonfly/server/item"
	"github.com/df-mc/dragonfly/server/world"
)

var Blocks = map[string]world.Block{
	"air":               block.Air{},
	"stone":             block.Stone{},
	"granite":           block.Granite{},
	"polished_granite":  block.Granite{Polished: true},
	"diorite":           block.Diorite{},
	"polished_diorite":  block.Diorite{Polished: true},
	"andesite":          block.Andesite{},
	"polished_andesite": block.Andesite{Polished: true},
	"grass_block":       block.Grass{},
	"dirt":              block.Dirt{},
	"coarse_dirt":       block.Dirt{Coarse: true},
	"podzol":            block.Podzol{},
	"cobblestone":       block.Cobblestone{},
	"oak_planks":        block.Planks{Wood: block.OakWood()},
	"spruce_planks":     block.Planks{Wood: block.SpruceWood()},
	"birch_planks":      block.Planks{Wood: block.BirchWood()},
	"jungle_planks":     block.Planks{Wood: block.JungleWood()},
	"acacia_planks":     block.Planks{Wood: block.AcaciaWood()},
	"dark_oak_planks":   block.Planks{Wood: block.DarkOakWood()},
	"mangrove_planks":   block.Planks{Wood: block.Mangrove()},
	//"oak_sapling":                        block.OakSapling{},
	//"spruce_sapling":                     block.SpruceSapling{},
	//"birch_sapling":                      block.BirchSapling{},
	//"jungle_sapling":                     block.JungleSapling{},
	//"acacia_sapling":                     block.AcaciaSapling{},
	//"dark_oak_sapling":                   block.DarkOakSapling{},
	//"mangrove_propagule":                 block.MangrovePropagule{},
	"bedrock":            block.Bedrock{},
	"water":              block.Water{},
	"lava":               block.Lava{},
	"sand":               block.Sand{},
	"red_sand":           block.Sand{Red: true},
	"gravel":             block.Gravel{},
	"gold_ore":           block.GoldOre{},
	"deepslate_gold_ore": block.GoldOre{Type: block.DeepslateOre()},
	"iron_ore":           block.IronOre{},
	"deepslate_iron_ore": block.IronOre{Type: block.DeepslateOre()},
	"coal_ore":           block.CoalOre{},
	"deepslate_coal_ore": block.CoalOre{Type: block.DeepslateOre()},
	"nether_gold_ore":    block.NetherGoldOre{},
	"oak_log":            block.Log{Wood: block.OakWood()},
	"spruce_log":         block.Log{Wood: block.SpruceWood()},
	"birch_log":          block.Log{Wood: block.BirchWood()},
	"jungle_log":         block.Log{Wood: block.JungleWood()},
	"acacia_log":         block.Log{Wood: block.AcaciaWood()},
	"dark_oak_log":       block.Log{Wood: block.DarkOakWood()},
	"mangrove_log":       block.Log{Wood: block.Mangrove()},
	//"mangrove_roots":                     block.MangroveRoots{},
	"muddy_mangrove_roots":   block.MuddyMangroveRoots{},
	"stripped_spruce_log":    block.Log{},
	"stripped_birch_log":     block.Log{Wood: block.OakWood(), Stripped: true},
	"stripped_jungle_log":    block.Log{Wood: block.SpruceWood(), Stripped: true},
	"stripped_acacia_log":    block.Log{Wood: block.BirchWood(), Stripped: true},
	"stripped_dark_oak_log":  block.Log{Wood: block.JungleWood(), Stripped: true},
	"stripped_oak_log":       block.Log{Wood: block.AcaciaWood(), Stripped: true},
	"stripped_mangrove_log":  block.Log{Wood: block.DarkOakWood(), Stripped: true},
	"oak_wood":               block.Wood{Wood: block.OakWood()},
	"spruce_wood":            block.Wood{Wood: block.SpruceWood()},
	"birch_wood":             block.Wood{Wood: block.BirchWood()},
	"jungle_wood":            block.Wood{Wood: block.JungleWood()},
	"acacia_wood":            block.Wood{Wood: block.AcaciaWood()},
	"dark_oak_wood":          block.Wood{Wood: block.DarkOakWood()},
	"mangrove_wood":          block.Wood{Wood: block.Mangrove()},
	"stripped_oak_wood":      block.Wood{Wood: block.OakWood(), Stripped: true},
	"stripped_spruce_wood":   block.Wood{Wood: block.SpruceWood(), Stripped: true},
	"stripped_birch_wood":    block.Wood{Wood: block.BirchWood(), Stripped: true},
	"stripped_jungle_wood":   block.Wood{Wood: block.JungleWood(), Stripped: true},
	"stripped_acacia_wood":   block.Wood{Wood: block.AcaciaWood(), Stripped: true},
	"stripped_dark_oak_wood": block.Wood{Wood: block.DarkOakWood(), Stripped: true},
	"stripped_mangrove_wood": block.Wood{Wood: block.Mangrove(), Stripped: true},
	"oak_leaves":             block.Leaves{Wood: block.OakWood()},
	"spruce_leaves":          block.Leaves{Wood: block.SpruceWood()},
	"birch_leaves":           block.Leaves{Wood: block.BirchWood()},
	"jungle_leaves":          block.Leaves{Wood: block.JungleWood()},
	"acacia_leaves":          block.Leaves{Wood: block.AcaciaWood()},
	"dark_oak_leaves":        block.Leaves{Wood: block.DarkOakWood()},
	"mangrove_leaves":        block.Leaves{Wood: block.Mangrove()},
	//"azalea_leaves":                      block.Leaves{},
	//"flowering_azalea_leaves":            block.Leaves{},
	"sponge":              block.Sponge{},
	"wet_sponge":          block.Sponge{Wet: true},
	"glass":               block.Glass{},
	"lapis_ore":           block.LapisOre{},
	"deepslate_lapis_ore": block.LapisOre{Type: block.DeepslateOre()},
	"lapis_block":         block.Lapis{},
	//"dispenser":                          block.Dispenser{},
	"sandstone":          block.Sandstone{},
	"chiseled_sandstone": block.Sandstone{Type: block.ChiseledSandstone()},
	"cut_sandstone":      block.Sandstone{Type: block.CutSandstone()},
	"note_block":         block.Note{},
	//"white_bed":                          block.WhiteBed{},
	//"orange_bed":                         block.OrangeBed{},
	//"magenta_bed":                        block.MagentaBed{},
	//"light_blue_bed":                     block.LightBlueBed{},
	//"yellow_bed":                         block.YellowBed{},
	//"lime_bed":                           block.LimeBed{},
	//"pink_bed":                           block.PinkBed{},
	//"gray_bed":                           block.GrayBed{},
	//"light_gray_bed":                     block.LightGrayBed{},
	//"cyan_bed":                           block.CyanBed{},
	//"purple_bed":                         block.PurpleBed{},
	//"blue_bed":                           block.BlueBed{},
	//"brown_bed":                          block.BrownBed{},
	//"green_bed":                          block.GreenBed{},
	//"red_bed":                            block.RedBed{},
	//"black_bed":                          block.BlackBed{},
	//"powered_rail":                       block.PoweredRail{},
	//"detector_rail":                      block.DetectorRail{},
	//"sticky_piston":                      block.StickyPiston{},
	//"cobweb":                             block.Cobweb{},
	"grass": block.Grass{},
	//"fern":                               block.Fern{},
	"dead_bush": block.DeadBush{},
	//"seagrass":                           block.Seagrass{},
	//"tall_seagrass":                      block.TallSeagrass{},
	//"piston":                             block.Piston{},
	//"piston_head":                        block.PistonHead{},
	"white_wool":      block.Wool{Colour: item.ColourWhite()},
	"orange_wool":     block.Wool{Colour: item.ColourOrange()},
	"magenta_wool":    block.Wool{Colour: item.ColourMagenta()},
	"light_blue_wool": block.Wool{Colour: item.ColourLightBlue()},
	"yellow_wool":     block.Wool{Colour: item.ColourYellow()},
	"lime_wool":       block.Wool{Colour: item.ColourLime()},
	"pink_wool":       block.Wool{Colour: item.ColourPink()},
	"gray_wool":       block.Wool{Colour: item.ColourGrey()},
	"light_gray_wool": block.Wool{Colour: item.ColourLightGrey()},
	"cyan_wool":       block.Wool{Colour: item.ColourCyan()},
	"purple_wool":     block.Wool{Colour: item.ColourPurple()},
	"blue_wool":       block.Wool{Colour: item.ColourBlue()},
	"brown_wool":      block.Wool{Colour: item.ColourBrown()},
	"green_wool":      block.Wool{Colour: item.ColourGreen()},
	"red_wool":        block.Wool{Colour: item.ColourRed()},
	"black_wool":      block.Wool{Colour: item.ColourBlack()},
	//"moving_piston":                      block.MovingPiston{},
	"dandelion":          block.Flower{Type: block.Dandelion()},
	"poppy":              block.Flower{Type: block.Poppy()},
	"blue_orchid":        block.Flower{Type: block.BlueOrchid()},
	"allium":             block.Flower{Type: block.Allium()},
	"azure_bluet":        block.Flower{Type: block.AzureBluet()},
	"red_tulip":          block.Flower{Type: block.RedTulip()},
	"orange_tulip":       block.Flower{Type: block.OrangeTulip()},
	"white_tulip":        block.Flower{Type: block.WhiteTulip()},
	"pink_tulip":         block.Flower{Type: block.PinkTulip()},
	"oxeye_daisy":        block.Flower{Type: block.OxeyeDaisy()},
	"cornflower":         block.Flower{Type: block.Cornflower()},
	"wither_rose":        block.Flower{Type: block.WitherRose()},
	"lily_of_the_valley": block.Flower{Type: block.LilyOfTheValley()},
	//"brown_mushroom":                     block.BrownMushroom,
	//"red_mushroom":                       block.RedMushroom{},
	"gold_block":        block.Gold{},
	"iron_block":        block.Iron{},
	"bricks":            block.Bricks{},
	"tnt":               block.TNT{},
	"bookshelf":         block.Bookshelf{},
	"mossy_cobblestone": block.Cobblestone{Mossy: true},
	"obsidian":          block.Obsidian{},
	"torch":             block.Torch{},
	//"wall_torch":                         block.Torch{},
	"fire":      block.Fire{},
	"soul_fire": block.Fire{Type: block.SoulFire()},
	//"spawner":                            block.Spawner{},
	"oak_stairs": block.Stairs{Block: block.Wood{Wood: block.OakWood()}},
	"chest":      block.Chest{},
	//"redstone_wire":                      block.RedstoneWire{},
	"diamond_ore":           block.DiamondOre{},
	"deepslate_diamond_ore": block.DiamondOre{Type: block.DeepslateOre()},
	"diamond_block":         block.Diamond{},
	"crafting_table":        block.CraftingTable{},
	"wheat":                 block.WheatSeeds{},
	"farmland":              block.Farmland{},
	"furnace":               block.Furnace{},
	"oak_sign":              block.Sign{Wood: block.OakWood()},
	"spruce_sign":           block.Sign{Wood: block.SpruceWood()},
	"birch_sign":            block.Sign{Wood: block.BirchWood()},
	"acacia_sign":           block.Sign{Wood: block.JungleWood()},
	"jungle_sign":           block.Sign{Wood: block.AcaciaWood()},
	"dark_oak_sign":         block.Sign{Wood: block.DarkOakWood()},
	"mangrove_sign":         block.Sign{Wood: block.Mangrove()},
	"oak_door":              block.WoodDoor{Wood: block.OakWood()},
	"ladder":                block.Ladder{},
	//"rail":                               block.Rail{},
	"cobblestone_stairs": block.Stairs{Block: block.Cobblestone{}},
	"oak_wall_sign":      block.Sign{Wood: block.OakWood(), Attach: block.WallAttachment(cube.North)},
	"spruce_wall_sign":   block.Sign{Wood: block.SpruceWood(), Attach: block.WallAttachment(cube.North)},
	"birch_wall_sign":    block.Sign{Wood: block.BirchWood(), Attach: block.WallAttachment(cube.North)},
	"acacia_wall_sign":   block.Sign{Wood: block.JungleWood(), Attach: block.WallAttachment(cube.North)},
	"jungle_wall_sign":   block.Sign{Wood: block.AcaciaWood(), Attach: block.WallAttachment(cube.North)},
	"dark_oak_wall_sign": block.Sign{Wood: block.DarkOakWood(), Attach: block.WallAttachment(cube.North)},
	"mangrove_wall_sign": block.Sign{Wood: block.Mangrove(), Attach: block.WallAttachment(cube.North)},
	//"lever":                              block.Lever{},
	//"stone_pressure_plate":               block.StonePressurePlate{},
	//"iron_door":                          block.IronDoor{},
	//"oak_pressure_plate":                 block.OakPressurePlate{},
	//"spruce_pressure_plate":              block.SprucePressurePlate{},
	//"birch_pressure_plate":               block.BirchPressurePlate{},
	//"jungle_pressure_plate":              block.JunglePressurePlate{},
	//"acacia_pressure_plate":              block.AcaciaPressurePlate{},
	//"dark_oak_pressure_plate":            block.DarkOakPressurePlate{},
	//"mangrove_pressure_plate":            block.MangrovePressurePlate{},
	//"redstone_ore":                       block.RedstoneOre{},
	//"deepslate_redstone_ore":             block.DeepslateRedstoneOre{},
	//"redstone_torch":                     block.RedstoneTorch{},
	//"redstone_wall_torch":                block.RedstoneWallTorch{},
	//"stone_button":                       block.StoneButton{},
	"snow": block.Snow{},
	//"ice":                                block.Ice{},
	"snow_block":      block.Snow{},
	"cactus":          block.Cactus{},
	"clay":            block.Clay{},
	"sugar_cane":      block.SugarCane{},
	"jukebox":         block.Jukebox{},
	"oak_fence":       block.WoodFence{Wood: block.OakWood()},
	"pumpkin":         block.Pumpkin{},
	"netherrack":      block.Netherrack{},
	"soul_sand":       block.SoulSand{},
	"soul_soil":       block.SoulSoil{},
	"basalt":          block.Basalt{},
	"polished_basalt": block.Basalt{Polished: true},
	"soul_torch":      block.Torch{Type: block.SoulFire()},
	//"soul_wall_torch":                    block.Torch{},
	"glowstone": block.Glowstone{},
	//"nether_portal":                      block.NetherPortal{},
	"carved_pumpkin": block.Pumpkin{Carved: true},
	"jack_o_lantern": block.Pumpkin{},
	"cake":           block.Cake{},
	//"repeater":                           block.Repeater{},
	"white_stained_glass":      block.StainedGlass{Colour: item.ColourWhite()},
	"orange_stained_glass":     block.StainedGlass{Colour: item.ColourOrange()},
	"magenta_stained_glass":    block.StainedGlass{Colour: item.ColourMagenta()},
	"light_blue_stained_glass": block.StainedGlass{Colour: item.ColourLightBlue()},
	"yellow_stained_glass":     block.StainedGlass{Colour: item.ColourYellow()},
	"lime_stained_glass":       block.StainedGlass{Colour: item.ColourLime()},
	"pink_stained_glass":       block.StainedGlass{Colour: item.ColourPink()},
	"gray_stained_glass":       block.StainedGlass{Colour: item.ColourGrey()},
	"light_gray_stained_glass": block.StainedGlass{Colour: item.ColourLightGrey()},
	"cyan_stained_glass":       block.StainedGlass{Colour: item.ColourCyan()},
	"purple_stained_glass":     block.StainedGlass{Colour: item.ColourPurple()},
	"blue_stained_glass":       block.StainedGlass{Colour: item.ColourBlue()},
	"brown_stained_glass":      block.StainedGlass{Colour: item.ColourBrown()},
	"green_stained_glass":      block.StainedGlass{Colour: item.ColourGreen()},
	"red_stained_glass":        block.StainedGlass{Colour: item.ColourRed()},
	"black_stained_glass":      block.StainedGlass{Colour: item.ColourBlack()},
	"oak_trapdoor":             block.WoodTrapdoor{Wood: block.OakWood()},
	"spruce_trapdoor":          block.WoodTrapdoor{Wood: block.SpruceWood()},
	"birch_trapdoor":           block.WoodTrapdoor{Wood: block.BirchWood()},
	"jungle_trapdoor":          block.WoodTrapdoor{Wood: block.JungleWood()},
	"acacia_trapdoor":          block.WoodTrapdoor{Wood: block.AcaciaWood()},
	"dark_oak_trapdoor":        block.WoodTrapdoor{Wood: block.DarkOakWood()},
	"mangrove_trapdoor":        block.WoodTrapdoor{Wood: block.Mangrove()},
	"stone_bricks":             block.StoneBricks{},
	"mossy_stone_bricks":       block.StoneBricks{Type: block.MossyStoneBricks()},
	"cracked_stone_bricks":     block.StoneBricks{Type: block.CrackedStoneBricks()},
	"chiseled_stone_bricks":    block.StoneBricks{Type: block.ChiseledStoneBricks()},
	"packed_mud":               block.PackedMud{},
	"mud_bricks":               block.MudBricks{},
	//"infested_stone":                     block.InfestedStone{},
	//"infested_cobblestone":               block.InfestedCobblestone{},
	//"infested_stone_bricks":              block.InfestedStoneBricks{},
	//"infested_mossy_stone_bricks":        block.InfestedMossyStoneBricks{},
	//"infested_cracked_stone_bricks":      block.InfestedCrackedStoneBricks{},
	//"infested_chiseled_stone_bricks":     block.InfestedChiseledStoneBricks{},
	//"brown_mushroom_block":               block.BrownMushroomBlock{},
	//"red_mushroom_block":                 block.RedMushroomBlock{},
	//"mushroom_stem":                      block.MushroomStem{},
	"iron_bars":  block.IronBars{},
	"chain":      block.Chain{},
	"glass_pane": block.GlassPane{},
	"melon":      block.Melon{},
	//"attached_pumpkin_stem":              block.AttachedPumpkinStem{},
	//"attached_melon_stem":                block.AttachedMelonStem{},
	//"pumpkin_stem":                       block.PumpkinStem{},
	//"melon_stem":                         block.MelonStem{},
	//"vine":                               block.Vine{},
	//"glow_lichen":                        block.GlowLichen{},
	"oak_fence_gate":     block.WoodFenceGate{Wood: block.OakWood()},
	"brick_stairs":       block.Stairs{Block: block.Bricks{}},
	"stone_brick_stairs": block.Stairs{Block: block.StoneBricks{}},
	"mud_brick_stairs":   block.Stairs{Block: block.MudBricks{}},
	//"mycelium":           block.Mycelium{},
	//"lily_pad":                           block.LilyPad{},
	"nether_bricks":       block.NetherBricks{},
	"nether_brick_fence":  block.NetherBrickFence{},
	"nether_brick_stairs": block.Stairs{Block: block.NetherBricks{}},
	"nether_wart":         block.NetherWart{},
	"enchanting_table":    block.EnchantingTable{},
	//"brewing_stand":                      block.BrewingStand{},
	//"cauldron":                           block.Cauldron{},
	//"water_cauldron":                     block.WaterCauldron{},
	//"lava_cauldron":                      block.LavaCauldron{},
	////"powder_snow_cauldron":               block.PowderSnowCauldron{},
	//"end_portal": block.EndPortal{},
	//"end_portal_frame":                   block.EndPortal{},
	"end_stone":  block.EndStone{},
	"dragon_egg": block.DragonEgg{},
	//"redstone_lamp":                      block.RedstoneLamp{},
	"cocoa":                 block.CocoaBean{},
	"sandstone_stairs":      block.Stairs{Block: block.Sandstone{}},
	"emerald_ore":           block.EmeraldOre{},
	"deepslate_emerald_ore": block.EmeraldOre{Type: block.DeepslateOre()},
	"ender_chest":           block.EnderChest{},
	//"tripwire_hook":                      block.TripwireHook{},
	//"tripwire":                           block.Tripwire{},
	"emerald_block": block.Emerald{},
	"spruce_stairs": block.Stairs{Block: block.Wood{Wood: block.SpruceWood()}},
	"birch_stairs":  block.Stairs{Block: block.Wood{Wood: block.BirchWood()}},
	"jungle_stairs": block.Stairs{Block: block.Wood{Wood: block.JungleWood()}},
	//"command_block":                      block.CommandBlock{},
	"beacon":                 block.Beacon{},
	"cobblestone_wall":       block.Wall{Block: block.Cobblestone{}},
	"mossy_cobblestone_wall": block.Wall{Block: block.Cobblestone{Mossy: true}},
	//"flower_pot":                         block.FlowerPot{},
	//"potted_oak_sapling":                 block.PottedOakSapling{},
	//"potted_spruce_sapling":              block.PottedSpruceSapling{},
	//"potted_birch_sapling":               block.PottedBirchSapling{},
	//"potted_jungle_sapling":              block.PottedJungleSapling{},
	//"potted_acacia_sapling":              block.PottedAcaciaSapling{},
	//"potted_dark_oak_sapling":            block.PottedDarkOakSapling{},
	//"potted_mangrove_propagule":          block.PottedMangrovePropagule{},
	//"potted_fern":                        block.PottedFern{},
	//"potted_dandelion":                   block.PottedDandelion{},
	//"potted_poppy":                       block.PottedPoppy{},
	//"potted_blue_orchid":                 block.PottedBlueOrchid{},
	//"potted_allium":                      block.PottedAllium{},
	//"potted_azure_bluet":                 block.PottedAzureBluet{},
	//"potted_red_tulip":                   block.PottedRedTulip{},
	//"potted_orange_tulip":                block.PottedOrangeTulip{},
	//"potted_white_tulip":                 block.PottedWhiteTulip{},
	//"potted_pink_tulip":                  block.PottedPinkTulip{},
	//"potted_oxeye_daisy":                 block.PottedOxeyeDaisy{},
	//"potted_cornflower":                  block.PottedCornflower{},
	//"potted_lily_of_the_valley":          block.PottedLilyOfTheValley{},
	//"potted_wither_rose":                 block.PottedWitherRose{},
	//"potted_red_mushroom":                block.PottedRedMushroom{},
	//"potted_brown_mushroom":              block.PottedBrownMushroom{},
	//"potted_dead_bush":                   block.PottedDeadBush{},
	//"potted_cactus":                      block.PottedCactus{},
	"carrots":  block.Carrot{},
	"potatoes": block.Potato{},
	//"oak_button":                         block.OakButton{},
	//"spruce_button":                      block.SpruceButton{},
	//"birch_button":                       block.BirchButton{},
	//"jungle_button":                      block.JungleButton{},
	//"acacia_button":                      block.AcaciaButton{},
	//"dark_oak_button":                    block.DarkOakButton{},
	//"mangrove_button":                    block.MangroveButton{},
	"skeleton_skull":             block.Skull{Type: block.SkeletonSkull()},
	"skeleton_wall_skull":        block.Skull{Type: block.SkeletonSkull(), Attach: block.WallAttachment(cube.North)},
	"wither_skeleton_skull":      block.Skull{Type: block.WitherSkeletonSkull()},
	"wither_skeleton_wall_skull": block.Skull{Type: block.WitherSkeletonSkull(), Attach: block.WallAttachment(cube.North)},
	"zombie_head":                block.Skull{Type: block.ZombieHead()},
	"zombie_wall_head":           block.Skull{Type: block.ZombieHead(), Attach: block.WallAttachment(cube.North)},
	"player_head":                block.Skull{Type: block.PlayerHead()},
	"player_wall_head":           block.Skull{Type: block.PlayerHead(), Attach: block.WallAttachment(cube.North)},
	"creeper_head":               block.Skull{Type: block.CreeperHead()},
	"creeper_wall_head":          block.Skull{Type: block.CreeperHead(), Attach: block.WallAttachment(cube.North)},
	"dragon_head":                block.Skull{Type: block.DragonHead()},
	"dragon_wall_head":           block.Skull{Type: block.DragonHead(), Attach: block.WallAttachment(cube.North)},
	"anvil":                      block.Anvil{},
	"chipped_anvil":              block.Anvil{Type: block.SlightlyDamagedAnvil()},
	"damaged_anvil":              block.Anvil{Type: block.VeryDamagedAnvil()},
	"trapped_chest":              block.Chest{},
	//"light_weighted_pressure_plate":      block.LightWeightedPressurePlate{},
	//"heavy_weighted_pressure_plate":      block.HeavyWeightedPressurePlate{},
	//"comparator":                         block.Comparator{},
	//"daylight_detector":                  block.DaylightDetector{},
	//"redstone_block":                     block.RedstoneBlock{},
	"nether_quartz_ore": block.NetherQuartzOre{},
	//"hopper":                             block.Hopper{},
	"quartz_block":          block.Quartz{},
	"chiseled_quartz_block": block.ChiseledQuartz{},
	"quartz_pillar":         block.QuartzPillar{},
	"quartz_stairs":         block.Stairs{Block: block.Quartz{}},
	//"activator_rail":                     block.ActivatorRail{},
	//"dropper":                            block.Dropper{},
	"white_terracotta":              block.StainedTerracotta{Colour: item.ColourWhite()},
	"orange_terracotta":             block.StainedTerracotta{Colour: item.ColourOrange()},
	"magenta_terracotta":            block.StainedTerracotta{Colour: item.ColourMagenta()},
	"light_blue_terracotta":         block.StainedTerracotta{Colour: item.ColourLightBlue()},
	"yellow_terracotta":             block.StainedTerracotta{Colour: item.ColourYellow()},
	"lime_terracotta":               block.StainedTerracotta{Colour: item.ColourLime()},
	"pink_terracotta":               block.StainedTerracotta{Colour: item.ColourPink()},
	"gray_terracotta":               block.StainedTerracotta{Colour: item.ColourGrey()},
	"light_gray_terracotta":         block.StainedTerracotta{Colour: item.ColourLightGrey()},
	"cyan_terracotta":               block.StainedTerracotta{Colour: item.ColourCyan()},
	"purple_terracotta":             block.StainedTerracotta{Colour: item.ColourPurple()},
	"blue_terracotta":               block.StainedTerracotta{Colour: item.ColourBlue()},
	"brown_terracotta":              block.StainedTerracotta{Colour: item.ColourBrown()},
	"green_terracotta":              block.StainedTerracotta{Colour: item.ColourGreen()},
	"red_terracotta":                block.StainedTerracotta{Colour: item.ColourRed()},
	"black_terracotta":              block.StainedTerracotta{Colour: item.ColourBlack()},
	"white_stained_glass_pane":      block.StainedGlassPane{Colour: item.ColourWhite()},
	"orange_stained_glass_pane":     block.StainedGlassPane{Colour: item.ColourOrange()},
	"magenta_stained_glass_pane":    block.StainedGlassPane{Colour: item.ColourMagenta()},
	"light_blue_stained_glass_pane": block.StainedGlassPane{Colour: item.ColourLightBlue()},
	"yellow_stained_glass_pane":     block.StainedGlassPane{Colour: item.ColourYellow()},
	"lime_stained_glass_pane":       block.StainedGlassPane{Colour: item.ColourLime()},
	"pink_stained_glass_pane":       block.StainedGlassPane{Colour: item.ColourPink()},
	"gray_stained_glass_pane":       block.StainedGlassPane{Colour: item.ColourGrey()},
	"light_gray_stained_glass_pane": block.StainedGlassPane{Colour: item.ColourLightGrey()},
	"cyan_stained_glass_pane":       block.StainedGlassPane{Colour: item.ColourCyan()},
	"purple_stained_glass_pane":     block.StainedGlassPane{Colour: item.ColourPurple()},
	"blue_stained_glass_pane":       block.StainedGlassPane{Colour: item.ColourBlue()},
	"brown_stained_glass_pane":      block.StainedGlassPane{Colour: item.ColourBrown()},
	"green_stained_glass_pane":      block.StainedGlassPane{Colour: item.ColourGreen()},
	"red_stained_glass_pane":        block.StainedGlassPane{Colour: item.ColourRed()},
	"black_stained_glass_pane":      block.StainedGlassPane{Colour: item.ColourBlack()},
	"acacia_stairs":                 block.Stairs{Block: block.Wood{Wood: block.AcaciaWood()}},
	"dark_oak_stairs":               block.Stairs{Block: block.Wood{Wood: block.DarkOakWood()}},
	"mangrove_stairs":               block.Stairs{Block: block.Wood{Wood: block.Mangrove()}},
	//"slime_block":                        block.SlimeBlock{},
	"barrier": block.Barrier{},
	"light":   block.Light{},
	//"iron_trapdoor":                      block.Trap{},
	"prismarine":              block.Prismarine{},
	"prismarine_bricks":       block.Prismarine{Type: block.BrickPrismarine()},
	"dark_prismarine":         block.Prismarine{Type: block.DarkPrismarine()},
	"prismarine_stairs":       block.Stairs{Block: block.Prismarine{}},
	"prismarine_brick_stairs": block.Stairs{Block: block.Prismarine{Type: block.BrickPrismarine()}},
	"dark_prismarine_stairs":  block.Stairs{Block: block.Prismarine{Type: block.DarkPrismarine()}},
	"prismarine_slab":         block.Slab{Block: block.Prismarine{}},
	"prismarine_brick_slab":   block.Slab{Block: block.Prismarine{Type: block.BrickPrismarine()}},
	"dark_prismarine_slab":    block.Slab{Block: block.Prismarine{Type: block.DarkPrismarine()}},
	"sea_lantern":             block.SeaLantern{},
	"hay_block":               block.HayBale{},
	"white_carpet":            block.Carpet{Colour: item.ColourWhite()},
	"orange_carpet":           block.Carpet{Colour: item.ColourOrange()},
	"magenta_carpet":          block.Carpet{Colour: item.ColourMagenta()},
	"light_blue_carpet":       block.Carpet{Colour: item.ColourLightBlue()},
	"yellow_carpet":           block.Carpet{Colour: item.ColourYellow()},
	"lime_carpet":             block.Carpet{Colour: item.ColourLime()},
	"pink_carpet":             block.Carpet{Colour: item.ColourPink()},
	"gray_carpet":             block.Carpet{Colour: item.ColourGrey()},
	"light_gray_carpet":       block.Carpet{Colour: item.ColourLightGrey()},
	"cyan_carpet":             block.Carpet{Colour: item.ColourCyan()},
	"purple_carpet":           block.Carpet{Colour: item.ColourPurple()},
	"blue_carpet":             block.Carpet{Colour: item.ColourBlue()},
	"brown_carpet":            block.Carpet{Colour: item.ColourBrown()},
	"green_carpet":            block.Carpet{Colour: item.ColourGreen()},
	"red_carpet":              block.Carpet{Colour: item.ColourRed()},
	"black_carpet":            block.Carpet{Colour: item.ColourBlack()},
	"terracotta":              block.Terracotta{},
	"coal_block":              block.Coal{},
	"packed_ice":              block.PackedIce{},
	"sunflower":               block.DoubleFlower{Type: block.Sunflower()},
	"lilac":                   block.DoubleFlower{Type: block.Lilac()},
	"rose_bush":               block.DoubleFlower{Type: block.RoseBush()},
	"peony":                   block.DoubleFlower{Type: block.Peony()},
	"tall_grass":              block.TallGrass{},
	//"large_fern":                         block.Fern{},
	"white_banner":           block.Banner{Colour: item.ColourWhite()},
	"orange_banner":          block.Banner{Colour: item.ColourOrange()},
	"magenta_banner":         block.Banner{Colour: item.ColourMagenta()},
	"light_blue_banner":      block.Banner{Colour: item.ColourLightBlue()},
	"yellow_banner":          block.Banner{Colour: item.ColourYellow()},
	"lime_banner":            block.Banner{Colour: item.ColourLime()},
	"pink_banner":            block.Banner{Colour: item.ColourPink()},
	"gray_banner":            block.Banner{Colour: item.ColourGrey()},
	"light_gray_banner":      block.Banner{Colour: item.ColourLightGrey()},
	"cyan_banner":            block.Banner{Colour: item.ColourCyan()},
	"purple_banner":          block.Banner{Colour: item.ColourPurple()},
	"blue_banner":            block.Banner{Colour: item.ColourBlue()},
	"brown_banner":           block.Banner{Colour: item.ColourBrown()},
	"green_banner":           block.Banner{Colour: item.ColourGreen()},
	"red_banner":             block.Banner{Colour: item.ColourRed()},
	"black_banner":           block.Banner{Colour: item.ColourBlack()},
	"white_wall_banner":      block.Banner{Colour: item.ColourWhite(), Attach: block.WallAttachment(cube.North)},
	"orange_wall_banner":     block.Banner{Colour: item.ColourOrange(), Attach: block.WallAttachment(cube.North)},
	"magenta_wall_banner":    block.Banner{Colour: item.ColourMagenta(), Attach: block.WallAttachment(cube.North)},
	"light_blue_wall_banner": block.Banner{Colour: item.ColourLightBlue(), Attach: block.WallAttachment(cube.North)},
	"yellow_wall_banner":     block.Banner{Colour: item.ColourYellow(), Attach: block.WallAttachment(cube.North)},
	"lime_wall_banner":       block.Banner{Colour: item.ColourLime(), Attach: block.WallAttachment(cube.North)},
	"pink_wall_banner":       block.Banner{Colour: item.ColourPink(), Attach: block.WallAttachment(cube.North)},
	"gray_wall_banner":       block.Banner{Colour: item.ColourGrey(), Attach: block.WallAttachment(cube.North)},
	"light_gray_wall_banner": block.Banner{Colour: item.ColourLightGrey(), Attach: block.WallAttachment(cube.North)},
	"cyan_wall_banner":       block.Banner{Colour: item.ColourCyan(), Attach: block.WallAttachment(cube.North)},
	"purple_wall_banner":     block.Banner{Colour: item.ColourPurple(), Attach: block.WallAttachment(cube.North)},
	"blue_wall_banner":       block.Banner{Colour: item.ColourBlue(), Attach: block.WallAttachment(cube.North)},
	"brown_wall_banner":      block.Banner{Colour: item.ColourBrown(), Attach: block.WallAttachment(cube.North)},
	"green_wall_banner":      block.Banner{Colour: item.ColourGreen(), Attach: block.WallAttachment(cube.North)},
	"red_wall_banner":        block.Banner{Colour: item.ColourRed(), Attach: block.WallAttachment(cube.North)},
	"black_wall_banner":      block.Banner{Colour: item.ColourBlack(), Attach: block.WallAttachment(cube.North)},
	"red_sandstone":          block.Sandstone{Red: true},
	"chiseled_red_sandstone": block.Sandstone{Red: true, Type: block.ChiseledSandstone()},
	"cut_red_sandstone":      block.Sandstone{Red: true, Type: block.CutSandstone()},
	"red_sandstone_stairs":   block.Stairs{Block: block.Sandstone{Red: true}},
	"oak_slab":               block.Slab{Block: block.Wood{Wood: block.OakWood()}},
	"spruce_slab":            block.Slab{Block: block.Wood{Wood: block.SpruceWood()}},
	"birch_slab":             block.Slab{Block: block.Wood{Wood: block.BirchWood()}},
	"jungle_slab":            block.Slab{Block: block.Wood{Wood: block.JungleWood()}},
	"acacia_slab":            block.Slab{Block: block.Wood{Wood: block.AcaciaWood()}},
	"dark_oak_slab":          block.Slab{Block: block.Wood{Wood: block.DarkOakWood()}},
	"mangrove_slab":          block.Slab{Block: block.Wood{Wood: block.Mangrove()}},
	"stone_slab":             block.Slab{Block: block.Stone{}},
	"smooth_stone_slab":      block.Slab{Block: block.Stone{Smooth: true}},
	"sandstone_slab":         block.Slab{Block: block.Sandstone{}},
	"cut_sandstone_slab":     block.Slab{Block: block.Sandstone{Type: block.CutSandstone()}},
	//"petrified_oak_slab":                 block.Slab{Block: block.},
	"cobblestone_slab":       block.Slab{Block: block.Cobblestone{}},
	"brick_slab":             block.Slab{Block: block.Bricks{}},
	"stone_brick_slab":       block.Slab{Block: block.StoneBricks{}},
	"mud_brick_slab":         block.Slab{Block: block.MudBricks{}},
	"nether_brick_slab":      block.Slab{Block: block.NetherBricks{}},
	"quartz_slab":            block.Slab{Block: block.Quartz{}},
	"red_sandstone_slab":     block.Slab{Block: block.Sandstone{Red: true}},
	"cut_red_sandstone_slab": block.Slab{Block: block.Sandstone{Red: true, Type: block.CutSandstone()}},
	"purpur_slab":            block.Slab{Block: block.Purpur{}},
	"smooth_stone":           block.Stone{Smooth: true},
	"smooth_sandstone":       block.Sandstone{Type: block.SmoothSandstone()},
	"smooth_quartz":          block.Quartz{Smooth: true},
	"smooth_red_sandstone":   block.Sandstone{Red: true, Type: block.SmoothSandstone()},
	"spruce_fence_gate":      block.WoodFenceGate{Wood: block.SpruceWood()},
	"birch_fence_gate":       block.WoodFenceGate{Wood: block.BirchWood()},
	"jungle_fence_gate":      block.WoodFenceGate{Wood: block.JungleWood()},
	"acacia_fence_gate":      block.WoodFenceGate{Wood: block.AcaciaWood()},
	"dark_oak_fence_gate":    block.WoodFenceGate{Wood: block.DarkOakWood()},
	"mangrove_fence_gate":    block.WoodFenceGate{Wood: block.Mangrove()},
	"spruce_fence":           block.WoodFence{Wood: block.SpruceWood()},
	"birch_fence":            block.WoodFence{Wood: block.BirchWood()},
	"jungle_fence":           block.WoodFence{Wood: block.JungleWood()},
	"acacia_fence":           block.WoodFence{Wood: block.AcaciaWood()},
	"dark_oak_fence":         block.WoodFence{Wood: block.DarkOakWood()},
	"mangrove_fence":         block.WoodFence{Wood: block.Mangrove()},
	"spruce_door":            block.WoodDoor{Wood: block.SpruceWood()},
	"birch_door":             block.WoodDoor{Wood: block.BirchWood()},
	"jungle_door":            block.WoodDoor{Wood: block.JungleWood()},
	"acacia_door":            block.WoodDoor{Wood: block.AcaciaWood()},
	"dark_oak_door":          block.WoodDoor{Wood: block.DarkOakWood()},
	"mangrove_door":          block.WoodDoor{Wood: block.Mangrove()},
	//"end_rod":                            block.EndRod{},
	//"chorus_plant":                       block.ChorusPlant{},
	//"chorus_flower":                      block.ChorusFlower{},
	"purpur_block":     block.Purpur{},
	"purpur_pillar":    block.PurpurPillar{},
	"purpur_stairs":    block.Stairs{Block: block.Purpur{}},
	"end_stone_bricks": block.EndBricks{},
	"beetroots":        block.BeetrootSeeds{},
	"dirt_path":        block.DirtPath{},
	//"end_gateway":                        block.EndGateway{},
	//"repeating_command_block":            block.RepeatingCommandBlock{},
	//"chain_command_block":                block.ChainCommandBlock{},
	//"frosted_ice":                        block.FrostedIce{},
	//"magma_block":                        block.MagmaBlock{},
	"nether_wart_block": block.NetherWartBlock{},
	"red_nether_bricks": block.NetherBricks{Type: block.RedNetherBricks()},
	"bone_block":        block.Bone{},
	//"structure_void":                     block.StructureVoid{},
	//"observer":                           block.Observer{},
	//"shulker_box":                        block.ShulkerBox{},
	//"white_shulker_box":                  block.WhiteShulkerBox{},
	//"orange_shulker_box":                 block.OrangeShulkerBox{},
	//"magenta_shulker_box":                block.MagentaShulkerBox{},
	//"light_blue_shulker_box":             block.LightBlueShulkerBox{},
	//"yellow_shulker_box":                 block.YellowShulkerBox{},
	//"lime_shulker_box":                   block.LimeShulkerBox{},
	//"pink_shulker_box":                   block.PinkShulkerBox{},
	//"gray_shulker_box":                   block.GrayShulkerBox{},
	//"light_gray_shulker_box":             block.LightGrayShulkerBox{},
	//"cyan_shulker_box":                   block.CyanShulkerBox{},
	//"purple_shulker_box":                 block.PurpleShulkerBox{},
	//"blue_shulker_box":                   block.BlueShulkerBox{},
	//"brown_shulker_box":                  block.BrownShulkerBox{},
	//"green_shulker_box":                  block.GreenShulkerBox{},
	//"red_shulker_box":                    block.RedShulkerBox{},
	//"black_shulker_box":                  block.BlackShulkerBox{},
	"white_glazed_terracotta":      block.GlazedTerracotta{Colour: item.ColourWhite()},
	"orange_glazed_terracotta":     block.GlazedTerracotta{Colour: item.ColourOrange()},
	"magenta_glazed_terracotta":    block.GlazedTerracotta{Colour: item.ColourMagenta()},
	"light_blue_glazed_terracotta": block.GlazedTerracotta{Colour: item.ColourLightBlue()},
	"yellow_glazed_terracotta":     block.GlazedTerracotta{Colour: item.ColourYellow()},
	"lime_glazed_terracotta":       block.GlazedTerracotta{Colour: item.ColourLime()},
	"pink_glazed_terracotta":       block.GlazedTerracotta{Colour: item.ColourPink()},
	"gray_glazed_terracotta":       block.GlazedTerracotta{Colour: item.ColourGrey()},
	"light_gray_glazed_terracotta": block.GlazedTerracotta{Colour: item.ColourLightGrey()},
	"cyan_glazed_terracotta":       block.GlazedTerracotta{Colour: item.ColourCyan()},
	"purple_glazed_terracotta":     block.GlazedTerracotta{Colour: item.ColourPurple()},
	"blue_glazed_terracotta":       block.GlazedTerracotta{Colour: item.ColourBlue()},
	"brown_glazed_terracotta":      block.GlazedTerracotta{Colour: item.ColourBrown()},
	"green_glazed_terracotta":      block.GlazedTerracotta{Colour: item.ColourGreen()},
	"red_glazed_terracotta":        block.GlazedTerracotta{Colour: item.ColourRed()},
	"black_glazed_terracotta":      block.GlazedTerracotta{Colour: item.ColourBlack()},
	"white_concrete":               block.Concrete{Colour: item.ColourWhite()},
	"orange_concrete":              block.Concrete{Colour: item.ColourOrange()},
	"magenta_concrete":             block.Concrete{Colour: item.ColourMagenta()},
	"light_blue_concrete":          block.Concrete{Colour: item.ColourLightBlue()},
	"yellow_concrete":              block.Concrete{Colour: item.ColourYellow()},
	"lime_concrete":                block.Concrete{Colour: item.ColourLime()},
	"pink_concrete":                block.Concrete{Colour: item.ColourPink()},
	"gray_concrete":                block.Concrete{Colour: item.ColourGrey()},
	"light_gray_concrete":          block.Concrete{Colour: item.ColourLightGrey()},
	"cyan_concrete":                block.Concrete{Colour: item.ColourCyan()},
	"purple_concrete":              block.Concrete{Colour: item.ColourPurple()},
	"blue_concrete":                block.Concrete{Colour: item.ColourBlue()},
	"brown_concrete":               block.Concrete{Colour: item.ColourBrown()},
	"green_concrete":               block.Concrete{Colour: item.ColourGreen()},
	"red_concrete":                 block.Concrete{Colour: item.ColourRed()},
	"black_concrete":               block.Concrete{Colour: item.ColourBlack()},
	"white_concrete_powder":        block.ConcretePowder{Colour: item.ColourWhite()},
	"orange_concrete_powder":       block.ConcretePowder{Colour: item.ColourOrange()},
	"magenta_concrete_powder":      block.ConcretePowder{Colour: item.ColourMagenta()},
	"light_blue_concrete_powder":   block.ConcretePowder{Colour: item.ColourLightBlue()},
	"yellow_concrete_powder":       block.ConcretePowder{Colour: item.ColourYellow()},
	"lime_concrete_powder":         block.ConcretePowder{Colour: item.ColourLime()},
	"pink_concrete_powder":         block.ConcretePowder{Colour: item.ColourPink()},
	"gray_concrete_powder":         block.ConcretePowder{Colour: item.ColourGrey()},
	"light_gray_concrete_powder":   block.ConcretePowder{Colour: item.ColourLightGrey()},
	"cyan_concrete_powder":         block.ConcretePowder{Colour: item.ColourCyan()},
	"purple_concrete_powder":       block.ConcretePowder{Colour: item.ColourPurple()},
	"blue_concrete_powder":         block.ConcretePowder{Colour: item.ColourBlue()},
	"brown_concrete_powder":        block.ConcretePowder{Colour: item.ColourBrown()},
	"green_concrete_powder":        block.ConcretePowder{Colour: item.ColourGreen()},
	"red_concrete_powder":          block.ConcretePowder{Colour: item.ColourRed()},
	"black_concrete_powder":        block.ConcretePowder{Colour: item.ColourBlack()},
	"kelp":                         block.Kelp{},
	//"kelp_plant":                         block.Kelp{},
	"dried_kelp_block": block.DriedKelp{},
	//"turtle_egg":                         block.TurtleEgg{},
	"dead_tube_coral_block":   block.CoralBlock{Type: block.TubeCoral(), Dead: true},
	"dead_brain_coral_block":  block.CoralBlock{Type: block.BrainCoral(), Dead: true},
	"dead_bubble_coral_block": block.CoralBlock{Type: block.BubbleCoral(), Dead: true},
	"dead_fire_coral_block":   block.CoralBlock{Type: block.FireCoral(), Dead: true},
	"dead_horn_coral_block":   block.CoralBlock{Type: block.HornCoral(), Dead: true},
	"tube_coral_block":        block.CoralBlock{Type: block.TubeCoral()},
	"brain_coral_block":       block.CoralBlock{Type: block.BrainCoral()},
	"bubble_coral_block":      block.CoralBlock{Type: block.BubbleCoral()},
	"fire_coral_block":        block.CoralBlock{Type: block.FireCoral()},
	"horn_coral_block":        block.CoralBlock{Type: block.HornCoral()},
	"dead_tube_coral":         block.Coral{Type: block.TubeCoral(), Dead: true},
	"dead_brain_coral":        block.Coral{Type: block.BrainCoral(), Dead: true},
	"dead_bubble_coral":       block.Coral{Type: block.BubbleCoral(), Dead: true},
	"dead_fire_coral":         block.Coral{Type: block.FireCoral(), Dead: true},
	"dead_horn_coral":         block.Coral{Type: block.HornCoral(), Dead: true},
	"tube_coral":              block.Coral{Type: block.TubeCoral()},
	"brain_coral":             block.Coral{Type: block.BrainCoral()},
	"bubble_coral":            block.Coral{Type: block.BubbleCoral()},
	"fire_coral":              block.Coral{Type: block.FireCoral()},
	"horn_coral":              block.Coral{Type: block.HornCoral()},
	//"dead_tube_coral_fan":        block.Coral{Type: },
	//"dead_brain_coral_fan":       block.Coral{Type: },
	//"dead_bubble_coral_fan":      block.Coral{Type: },
	//"dead_fire_coral_fan":        block.Coral{Type: },
	//"dead_horn_coral_fan":        block.Coral{Type: },
	//"tube_coral_fan":             block.TubeCoralFan{},
	//"brain_coral_fan":            block.BrainCoralFan{},
	//"bubble_coral_fan":           block.BubbleCoralFan{},
	//"fire_coral_fan":             block.FireCoralFan{},
	//"horn_coral_fan":             block.HornCoralFan{},
	//"dead_tube_coral_wall_fan":   block.DeadTubeCoralWallFan{},
	//"dead_brain_coral_wall_fan":  block.DeadBrainCoralWallFan{},
	//"dead_bubble_coral_wall_fan": block.DeadBubbleCoralWallFan{},
	//"dead_fire_coral_wall_fan":   block.DeadFireCoralWallFan{},
	//"dead_horn_coral_wall_fan":   block.DeadHornCoralWallFan{},
	//"tube_coral_wall_fan":        block.TubeCoralWallFan{},
	//"brain_coral_wall_fan":       block.BrainCoralWallFan{},
	//"bubble_coral_wall_fan":      block.BubbleCoralWallFan{},
	//"fire_coral_wall_fan":        block.FireCoralWallFan{},
	//"horn_coral_wall_fan":        block.HornCoralWallFan{},
	"sea_pickle": block.SeaPickle{},
	"blue_ice":   block.BlueIce{},
	//"conduit":                            block.Conduit{},
	//"bamboo_sapling":                     block.BambooSapling{},
	//"bamboo":                             block.Bamboo{},
	//"potted_bamboo":                      block.PottedBamboo{},
	//"void_air":                           block.VoidAir{},
	//"cave_air":                           block.CaveAir{},
	//"bubble_column":                      block.BubbleColumn{},
	"polished_granite_stairs":     block.Stairs{Block: block.Granite{Polished: true}},
	"smooth_red_sandstone_stairs": block.Stairs{Block: block.Sandstone{Red: true, Type: block.SmoothSandstone()}},
	"mossy_stone_brick_stairs":    block.Stairs{Block: block.StoneBricks{Type: block.MossyStoneBricks()}},
	"polished_diorite_stairs":     block.Stairs{Block: block.Diorite{Polished: true}},
	"mossy_cobblestone_stairs":    block.Stairs{Block: block.Cobblestone{Mossy: true}},
	"end_stone_brick_stairs":      block.Stairs{Block: block.EndBricks{}},
	"stone_stairs":                block.Stairs{Block: block.Stone{}},
	"smooth_sandstone_stairs":     block.Stairs{Block: block.Sandstone{Type: block.SmoothSandstone()}},
	"smooth_quartz_stairs":        block.Stairs{Block: block.Quartz{Smooth: true}},
	"granite_stairs":              block.Stairs{Block: block.Granite{}},
	"andesite_stairs":             block.Stairs{Block: block.Andesite{}},
	"red_nether_brick_stairs":     block.Stairs{Block: block.NetherBricks{Type: block.RedNetherBricks()}},
	"polished_andesite_stairs":    block.Stairs{Block: block.Andesite{Polished: true}},
	"diorite_stairs":              block.Stairs{Block: block.Diorite{}},
	"polished_granite_slab":       block.Slab{Block: block.Granite{Polished: true}},
	"smooth_red_sandstone_slab":   block.Slab{Block: block.Sandstone{Red: true, Type: block.SmoothSandstone()}},
	"mossy_stone_brick_slab":      block.Slab{Block: block.StoneBricks{Type: block.MossyStoneBricks()}},
	"polished_diorite_slab":       block.Slab{Block: block.Diorite{Polished: true}},
	"mossy_cobblestone_slab":      block.Slab{Block: block.Cobblestone{Mossy: true}},
	"end_stone_brick_slab":        block.Slab{Block: block.EndBricks{}},
	"smooth_sandstone_slab":       block.Slab{Block: block.Stone{}},
	"smooth_quartz_slab":          block.Slab{Block: block.Sandstone{Type: block.SmoothSandstone()}},
	"granite_slab":                block.Slab{Block: block.Quartz{Smooth: true}},
	"andesite_slab":               block.Slab{Block: block.Granite{}},
	"red_nether_brick_slab":       block.Slab{Block: block.Andesite{}},
	"polished_andesite_slab":      block.Slab{Block: block.NetherBricks{Type: block.RedNetherBricks()}},
	"diorite_slab":                block.Slab{Block: block.Andesite{Polished: true}},
	"brick_wall":                  block.Wall{Block: block.Bricks{}},
	"prismarine_wall":             block.Wall{Block: block.Prismarine{}},
	"red_sandstone_wall":          block.Wall{Block: block.Sandstone{Red: true}},
	"mossy_stone_brick_wall":      block.Wall{Block: block.StoneBricks{Type: block.MossyStoneBricks()}},
	"granite_wall":                block.Wall{Block: block.Granite{}},
	"stone_brick_wall":            block.Wall{Block: block.StoneBricks{}},
	"mud_brick_wall":              block.Wall{Block: block.MudBricks{}},
	"nether_brick_wall":           block.Wall{Block: block.NetherBricks{}},
	"andesite_wall":               block.Wall{Block: block.Andesite{}},
	"red_nether_brick_wall":       block.Wall{Block: block.NetherBricks{Type: block.RedNetherBricks()}},
	"sandstone_wall":              block.Wall{Block: block.Sandstone{}},
	"end_stone_brick_wall":        block.Wall{Block: block.EndBricks{}},
	"diorite_wall":                block.Wall{Block: block.Diorite{}},
	//"scaffolding":                        block.Scaffolding{},
	"loom":          block.Loom{},
	"barrel":        block.Barrel{},
	"smoker":        block.Smoker{},
	"blast_furnace": block.BlastFurnace{},
	//"cartography_table":                  block.CartographyTable{},
	"fletching_table": block.FletchingTable{},
	"grindstone":      block.Grindstone{},
	//"lectern":                            block.Lectern{},
	"smithing_table": block.SmithingTable{},
	"stonecutter":    block.Stonecutter{},
	//"bell":                               block.Bell{},
	"lantern":      block.Lantern{},
	"soul_lantern": block.Lantern{Type: block.SoulFire()},
	//"campfire":                           block.Campfire{},
	//"soul_campfire":                      block.SoulCampfire{},
	//"sweet_berry_bush":                   block.SweetBerryBush{},
	"warped_stem":            block.Log{Wood: block.WarpedWood()},
	"stripped_warped_stem":   block.Log{Wood: block.WarpedWood(), Stripped: true},
	"warped_hyphae":          block.Wood{Wood: block.WarpedWood()},
	"stripped_warped_hyphae": block.Wood{Wood: block.WarpedWood(), Stripped: true},
	"warped_nylium":          block.Wood{Wood: block.WarpedWood()},
	"warped_fungus":          block.Wood{Wood: block.WarpedWood(), Stripped: true},
	"warped_wart_block":      block.NetherWartBlock{Warped: true},
	//"warped_roots":			   block.
	"nether_sprouts":          block.NetherSprouts{},
	"crimson_stem":            block.Log{Wood: block.CrimsonWood()},
	"stripped_crimson_stem":   block.Log{Wood: block.CrimsonWood(), Stripped: true},
	"crimson_hyphae":          block.Wood{Wood: block.CrimsonWood()},
	"stripped_crimson_hyphae": block.Wood{Wood: block.CrimsonWood(), Stripped: true},
	"crimson_nylium":          block.Wood{Wood: block.CrimsonWood()},
	"crimson_fungus":          block.Wood{Wood: block.CrimsonWood(), Stripped: true},
	"shroomlight":             block.Shroomlight{},
	//"weeping_vines":           block.WeepingVines{},
	//"weeping_vines_plant":     block.WeepingVinesPlant{},
	//"twisting_vines":          block.TwistingVines{},
	//"twisting_vines_plant":    block.TwistingVinesPlant{},
	//"crimson_roots":           block.Roo{},
	"crimson_planks": block.Planks{Wood: block.CrimsonWood()},
	"warped_planks":  block.Planks{Wood: block.WarpedWood()},
	"crimson_slab":   block.Slab{Block: block.Wood{Wood: block.CrimsonWood()}},
	"warped_slab":    block.Slab{Block: block.Wood{Wood: block.CrimsonWood()}},
	//"crimson_pressure_plate":  block.CrimsonPressurePlate{},
	//"warped_pressure_plate":   block.WarpedPressurePlate{},
	"crimson_fence":      block.WoodFence{Wood: block.CrimsonWood()},
	"warped_fence":       block.WoodFence{Wood: block.WarpedWood()},
	"crimson_trapdoor":   block.WoodFence{Wood: block.CrimsonWood()},
	"warped_trapdoor":    block.WoodTrapdoor{Wood: block.WarpedWood()},
	"crimson_fence_gate": block.WoodFenceGate{Wood: block.CrimsonWood()}, //brb KK
	"warped_fence_gate":  block.WoodFenceGate{Wood: block.WarpedWood()},
	"crimson_stairs":     block.Stairs{Block: block.Wood{Wood: block.CrimsonWood()}},
	"warped_stairs":      block.Stairs{Block: block.Wood{Wood: block.WarpedWood()}},
	//"crimson_button":          block.CrimsonButton{},
	//"warped_button":           block.WarpedButton{},
	"crimson_door":      block.WoodDoor{Wood: block.CrimsonWood()},
	"warped_door":       block.WoodDoor{Wood: block.WarpedWood()},
	"crimson_sign":      block.Sign{Wood: block.CrimsonWood()},
	"warped_sign":       block.Sign{Wood: block.WarpedWood()},
	"crimson_wall_sign": block.Sign{Wood: block.CrimsonWood(), Attach: block.WallAttachment(cube.North)},
	"warped_wall_sign":  block.Sign{Wood: block.WarpedWood(), Attach: block.WallAttachment(cube.North)},
	//"structure_block":         block.StructureBlock{},
	//"jigsaw":                             block.Jigsaw{},
	"composter": block.Composter{},
	//"target":                             block.Target{},
	//"bee_nest":                           block.BeeNest{},
	//"beehive":                            block.Beehive{},
	//"honey_block":                        block.HoneyBlock{},
	"honeycomb_block": block.Honeycomb{},
	"netherite_block": block.Netherite{},
	"ancient_debris":  block.AncientDebris{},
	"crying_obsidian": block.Obsidian{Crying: true},
	//"respawn_anchor":                     block.RespawnAnchor{},
	//"potted_crimson_fungus":              block.PottedCrimsonFungus{},
	//"potted_warped_fungus":               block.PottedWarpedFungus{},
	//"potted_crimson_roots":               block.PottedCrimsonRoots{},
	//"potted_warped_roots":                block.PottedWarpedRoots{},
	//"lodestone":                          block.Lodestone{},
	"blackstone":                         block.Blackstone{},
	"blackstone_stairs":                  block.Stairs{Block: block.Blackstone{}},
	"blackstone_wall":                    block.Wall{Block: block.Blackstone{}},
	"blackstone_slab":                    block.Slab{Block: block.Blackstone{}},
	"polished_blackstone":                block.Blackstone{Type: block.PolishedBlackstone()},
	"polished_blackstone_bricks":         block.PolishedBlackstoneBrick{},
	"cracked_polished_blackstone_bricks": block.PolishedBlackstoneBrick{Cracked: true},
	"chiseled_polished_blackstone":       block.Blackstone{Type: block.ChiseledPolishedBlackstone()},
	"polished_blackstone_brick_slab":     block.Slab{Block: block.PolishedBlackstoneBrick{}},
	"polished_blackstone_brick_stairs":   block.Stairs{Block: block.PolishedBlackstoneBrick{}},
	"polished_blackstone_brick_wall":     block.Wall{Block: block.PolishedBlackstoneBrick{}},
	"gilded_blackstone":                  block.Blackstone{Type: block.GildedBlackstone()},
	"polished_blackstone_stairs":         block.Stairs{Block: block.Blackstone{Type: block.PolishedBlackstone()}},
	"polished_blackstone_slab":           block.Slab{Block: block.Blackstone{Type: block.PolishedBlackstone()}},
	//"polished_blackstone_pressure_plate": block.PolishedBlackstonePressurePlate{},
	//"polished_blackstone_button":         block.PolishedBlackstoneButton{},
	"polished_blackstone_wall": block.Wall{Block: block.Blackstone{Type: block.PolishedBlackstone()}},
	"chiseled_nether_bricks":   block.NetherBricks{Type: block.ChiseledNetherBricks()},
	"cracked_nether_bricks":    block.NetherBricks{Type: block.CrackedNetherBricks()},
	"quartz_bricks":            block.QuartzBricks{},
	//"candle":                             block.Candle{},
	//"white_candle":                       block.WhiteCandle{},
	//"orange_candle":                      block.OrangeCandle{},
	//"magenta_candle":                     block.MagentaCandle{},
	//"light_blue_candle":                  block.LightBlueCandle{},
	//"yellow_candle":                      block.YellowCandle{},
	//"lime_candle":                        block.LimeCandle{},
	//"pink_candle":                        block.PinkCandle{},
	//"gray_candle":                        block.GrayCandle{},
	//"light_gray_candle":                  block.LightGrayCandle{},
	//"cyan_candle":                        block.CyanCandle{},
	//"purple_candle":                      block.PurpleCandle{},
	//"blue_candle":                        block.BlueCandle{},
	//"brown_candle":                       block.BrownCandle{},
	//"green_candle":                       block.GreenCandle{},
	//"red_candle":                         block.RedCandle{},
	//"black_candle":                       block.BlackCandle{},
	//"candle_cake":                        block.CandleCake{},
	//"white_candle_cake":                  block.WhiteCandleCake{},
	//"orange_candle_cake":                 block.OrangeCandleCake{},
	//"magenta_candle_cake":                block.MagentaCandleCake{},
	//"light_blue_candle_cake":             block.LightBlueCandleCake{},
	//"yellow_candle_cake":                 block.YellowCandleCake{},
	//"lime_candle_cake":                   block.LimeCandleCake{},
	//"pink_candle_cake":                   block.PinkCandleCake{},
	//"gray_candle_cake":                   block.GrayCandleCake{},
	//"light_gray_candle_cake":             block.LightGrayCandleCake{},
	//"cyan_candle_cake":                   block.CyanCandleCake{},
	//"purple_candle_cake":                 block.PurpleCandleCake{},
	//"blue_candle_cake":                   block.BlueCandleCake{},
	//"brown_candle_cake":                  block.BrownCandleCake{},
	//"green_candle_cake":                  block.GreenCandleCake{},
	//"red_candle_cake":                    block.RedCandleCake{},
	//"black_candle_cake":                  block.BlackCandleCake{},
	"amethyst_block": block.Amethyst{},
	//"budding_amethyst":    block.Amethyst{},
	//"amethyst_cluster":    block.AmethystCluster{},
	//"large_amethyst_bud":  block.LargeAmethystBud{},
	//"medium_amethyst_bud": block.MediumAmethystBud{},
	//"small_amethyst_bud":  block.SmallAmethystBud{},
	"tuff":    block.Tuff{},
	"calcite": block.Calcite{},
	//"tinted_glass":        block.Glass{},
	//"powder_snow":         block.Snow{},
	//"sculk_sensor":        block.SculkSensor{},
	//"sculk":               block.Sculk{},
	//"sculk_vein":          block.SculkVein{},
	//"sculk_catalyst":      block.SculkCatalyst{},
	//"sculk_shrieker":      block.SculkShrieker{},
	//"oxidized_copper":                   block.OxidizedCopper{},
	//"weathered_copper":                  block.WeatheredCopper{},
	//"exposed_copper":                    block.ExposedCopper{},
	//"copper_block":                      block.Copper{},
	"copper_ore":           block.CopperOre{},
	"deepslate_copper_ore": block.CopperOre{Type: block.DeepslateOre()},
	//"oxidized_cut_copper":               block.OxidizedCutCopper{},
	//"weathered_cut_copper":              block.WeatheredCutCopper{},
	//"exposed_cut_copper":                block.ExposedCutCopper{},
	//"cut_copper":                        block.CutCopper{},
	//"oxidized_cut_copper_stairs":        block.OxidizedCutCopperStairs{},
	//"weathered_cut_copper_stairs":       block.WeatheredCutCopperStairs{},
	//"exposed_cut_copper_stairs":         block.ExposedCutCopperStairs{},
	//"cut_copper_stairs":                 block.CutCopperStairs{},
	//"oxidized_cut_copper_slab":          block.OxidizedCutCopperSlab{},
	//"weathered_cut_copper_slab":         block.WeatheredCutCopperSlab{},
	//"exposed_cut_copper_slab":           block.ExposedCutCopperSlab{},
	//"cut_copper_slab":                   block.CutCopperSlab{},
	//"waxed_copper_block":                block.WaxedCopperBlock{},
	//"waxed_weathered_copper":            block.WaxedWeatheredCopper{},
	//"waxed_exposed_copper":              block.WaxedExposedCopper{},
	//"waxed_oxidized_copper":             block.WaxedOxidizedCopper{},
	//"waxed_oxidized_cut_copper":         block.WaxedOxidizedCutCopper{},
	//"waxed_weathered_cut_copper":        block.WaxedWeatheredCutCopper{},
	//"waxed_exposed_cut_copper":          block.WaxedExposedCutCopper{},
	//"waxed_cut_copper":                  block.WaxedCutCopper{},
	//"waxed_oxidized_cut_copper_stairs":  block.WaxedOxidizedCutCopperStairs{},
	//"waxed_weathered_cut_copper_stairs": block.WaxedWeatheredCutCopperStairs{},
	//"waxed_exposed_cut_copper_stairs":   block.WaxedExposedCutCopperStairs{},
	//"waxed_cut_copper_stairs":           block.WaxedCutCopperStairs{},
	//"waxed_oxidized_cut_copper_slab":    block.WaxedOxidizedCutCopperSlab{},
	//"waxed_weathered_cut_copper_slab":   block.WaxedWeatheredCutCopperSlab{},
	//"waxed_exposed_cut_copper_slab":     block.WaxedExposedCutCopperSlab{},
	//"waxed_cut_copper_slab":             block.WaxedCutCopperSlab{},
	//"lightning_rod":             block.LightningRod{},
	//"pointed_dripstone":         block.PointedDripstone{},
	"dripstone_block": block.Dripstone{},
	//"cave_vines":                block.CaveVines{},
	//"cave_vines_plant":          block.CaveVinesPlant{},
	"spore_blossom": block.SporeBlossom{},
	//"azalea":                    block.Azalea{},
	//"flowering_azalea":          block.FloweringAzalea{},
	"moss_carpet": block.MossCarpet{},
	//"moss_block":                block.MossBlock{},
	//"big_dripleaf":              block.BigDripleaf{},
	//"big_dripleaf_stem":         block.BigDripleafStem{},
	//"small_dripleaf":            block.SmallDripleaf{},
	//"hanging_roots":             block.HangingRoots{},
	//"rooted_dirt":               block.RootedDirt{},
	"mud":                       block.Mud{},
	"deepslate":                 block.Deepslate{},
	"cobbled_deepslate":         block.Deepslate{Type: block.CobbledDeepslate()},
	"cobbled_deepslate_stairs":  block.Stairs{Block: block.Deepslate{Type: block.CobbledDeepslate()}},
	"cobbled_deepslate_slab":    block.Slab{Block: block.Deepslate{Type: block.CobbledDeepslate()}},
	"cobbled_deepslate_wall":    block.Wall{Block: block.Deepslate{Type: block.CobbledDeepslate()}},
	"polished_deepslate":        block.Deepslate{Type: block.PolishedDeepslate()},
	"polished_deepslate_stairs": block.Stairs{Block: block.Deepslate{Type: block.PolishedDeepslate()}},
	"polished_deepslate_slab":   block.Slab{Block: block.Deepslate{Type: block.PolishedDeepslate()}},
	"polished_deepslate_wall":   block.Wall{Block: block.Deepslate{Type: block.PolishedDeepslate()}},
	"deepslate_tiles":           block.DeepslateTiles{},
	"deepslate_tile_stairs":     block.Stairs{Block: block.DeepslateTiles{}},
	"deepslate_tile_slab":       block.Slab{Block: block.DeepslateTiles{}},
	"deepslate_tile_wall":       block.Wall{Block: block.DeepslateTiles{}},
	"deepslate_bricks":          block.DeepslateBricks{},
	"deepslate_brick_stairs":    block.Stairs{Block: block.DeepslateBricks{}},
	"deepslate_brick_slab":      block.Slab{Block: block.DeepslateBricks{}},
	"deepslate_brick_wall":      block.Wall{Block: block.DeepslateBricks{}},
	"chiseled_deepslate":        block.Deepslate{Type: block.ChiseledDeepslate()},
	"cracked_deepslate_bricks":  block.DeepslateBricks{Cracked: true},
	"cracked_deepslate_tiles":   block.DeepslateTiles{Cracked: true},
	//"infested_deepslate":                block.InfestedDeepslate{},
	//"smooth_basalt":                     block.Basalt{},
	"raw_iron_block":   block.RawIron{},
	"raw_copper_block": block.RawCopper{},
	"raw_gold_block":   block.RawGold{},
	//"potted_azalea_bush":                block.PottedAzaleaBush{},
	//"potted_flowering_azalea_bush":      block.PottedFloweringAzaleaBush{},
	"ochre_froglight":       block.Froglight{Type: block.Ochre()},
	"verdant_froglight":     block.Froglight{Type: block.Verdant()},
	"pearlescent_froglight": block.Froglight{Type: block.Pearlescent()},
	//"frogspawn":                         block.Frogspawn{},
	"reinforced_deepslate": block.ReinforcedDeepslate{},
}
