---
Settings:
    1v1-Duel-Length: 720
    Party-Duel-Length: 1440
    End-Game-Time: 4
    Ranked-Queue-Time: 5
    Kit-Command: kit {type} 1
    Global-Fight-Menu: true
Arenas:
    example:
        Level: example
        Author: example
        Positions:
            - 0:0:0
            - 1:0:1
        Kit-IDs:
            - 1