
[Network]
  Address = ":19132"

[Players]
  Folder = "players"
  MaxCount = 0
  MaximumChunkRadius = 32
  SaveData = false

[Resources]
  AutoBuildPack = true
  Folder = "resources"
  Required = false

[Server]
  AuthEnabled = true
  JoinMessage = "%v has joined the game"
  Name = "§aVersai Skyblock"
  QuitMessage = "%v has left the game"
  ShutdownMessage = "Server closed."

[World]
  Folder = "world"
  SaveData = true
