<?php

/*
 * Auto-generated by libasynql-def
 * Created from mysql.sql
 */

declare(strict_types=1);

namespace ARTulloss\VersaiSettings\Database;

interface Queries{
	/**
	 * <h4>Declared in:</h4>
	 * - C:/Users/Adam/Desktop/stuff/pocketmine/Redo 3/plugins/VersaiSettings/resources/mysql.sql:9
	 */
	public const INIT_PLAYERS = "init.players";

	/**
	 * <h4>Declared in:</h4>
	 * - C:/Users/Adam/Desktop/stuff/pocketmine/Redo 3/plugins/VersaiSettings/resources/mysql.sql:24
	 */
	public const INIT_SETTINGS = "init.settings";

	/**
	 * <h4>Declared in:</h4>
	 * - C:/Users/Adam/Desktop/stuff/pocketmine/Redo 3/plugins/VersaiSettings/resources/mysql.sql:40
	 *
	 * <h3>Variables</h3>
	 * - <code>:player_name</code> string, required in mysql.sql
	 */
	public const SELECT_INSERT_PLAYER = "select.insert.player";

	/**
	 * <h4>Declared in:</h4>
	 * - C:/Users/Adam/Desktop/stuff/pocketmine/Redo 3/plugins/VersaiSettings/resources/mysql.sql:54
	 *
	 * <h3>Variables</h3>
	 * - <code>:follow_particles</code> int, required in mysql.sql
	 * - <code>:hit_particles</code> int, required in mysql.sql
	 * - <code>:player_name</code> string, required in mysql.sql
	 * - <code>:scoreboard</code> bool, required in mysql.sql
	 * - <code>:bossbar</code> bool, required in mysql.sql
	 * - <code>:flight</code> bool, required in mysql.sql
	 * - <code>:tag_1</code> int, required in mysql.sql
	 * - <code>:tag_2</code> int, required in mysql.sql
	 * - <code>:tag_3</code> int, required in mysql.sql
	 * - <code>:cape</code> int, required in mysql.sql
	 */
	public const SELECT_INSERT_SETTINGS = "select.insert.settings";

	/**
	 * <h4>Declared in:</h4>
	 * - C:/Users/Adam/Desktop/stuff/pocketmine/Redo 3/plugins/VersaiSettings/resources/mysql.sql:35
	 *
	 * <h3>Variables</h3>
	 * - <code>:player_name</code> string, required in mysql.sql
	 */
	public const SELECT_PLAYER = "select.player";

	/**
	 * <h4>Declared in:</h4>
	 * - C:/Users/Adam/Desktop/stuff/pocketmine/Redo 3/plugins/VersaiSettings/resources/mysql.sql:30
	 *
	 * <h3>Variables</h3>
	 * - <code>:player_name</code> string, required in mysql.sql
	 */
	public const SELECT_SETTINGS = "select.settings";

}
