name: vSkyblock
description: This is a plugin that was made for Skyblock
author: Versai
authors: ["TLS Gorilla", "lovediverse"]
version: 0.0.1-ALPHA
api: 4.0.0
src-namespace-prefix: Skyblock
main: Skyblock\Main
permissions:
  skyblock:
    default: op
    description: "Allows the user to use the Skyblock plugin as a SuperAdmin"
  skyblock.command.enchant:
    default: true
    description: "Allows the user to use the enchant command"
  skyblock.command.craft:
    default: true
    description: "Allows the user to use the craft command"
  skyblock.command.island:
    default: true
    description: "Allows the user to use the basic island commands"
  skyblock.command.island.stats:
    default: true
    description: "Allows the user to use the island stats command"
  skyblock.command.island.info:
    default: op
    description: "Allows the user to use the island info command"