name: TwistedKits
main: ARTulloss\TwistedKits\Main
version: 1.0.2
api: 3.0.0
author: ARTulloss
description: Kits plugin for TwistedPvP
website: https://github.com/artulloss
permissions:
  twistedkits.bypass:
    description: Allow bypassing the cooldown
    default: op
  twistedkits.all:
    description: Allow using all kits
    default: op
  twistedkits.use.<kit>:
    description: Allow using <kit>
    default: op