
[Network]
  Address = ":19132"

[Players]
  Folder = "players"
  MaxCount = 0
  MaximumChunkRadius = 32
  SaveData = false

[Resources]
  AutoBuildPack = true
  Folder = "resources"
  Required = false

[Server]
  AuthEnabled = true
  JoinMessage = "§7[§a+§7] %v"
  Name = "Versai Build Server"
  QuitMessage = "§7[§c-§7] %v"
  ShutdownMessage = "Server closed."

[World]
  Folder = "world"
  SaveData = true
