---
name: vArenas
version: 1.0.1
main: Versai\arenas\Arenas
api: 4.0.0
permissions:
  arenas.command:
    default: op
  arenas.command.list:
    default: op
  arenas.command.info:
    default: op
  arenas.command.create:
    default: op
  arenas.command.remove:
    default: op
  arenas.command.set:
    default: op
...
