---
name: vCosmetics
main: Duo\vcosmetics\Main
api: 4.0.0
version: 1.0.0
author: Duo
description: Versai cosmetics!
permissions:
  cosmetics.settings.command:
    default: true
    description: Use /settings

  cosmetics.flight:
    default: op
# Tags
  
  cosmetics.tag.Eboy:
    default: op
  cosmetics.tag.Egirl:
    default: op
  cosmetics.tag.Mineman:
    default: op
  cosmetics.tag.God:
    default: op
  cosmetics.tag.OG:
    default: op
  cosmetics.tag.Idot:
    default: op
  cosmetics.tag.MapMaker:
    default: op
  cosmetics.tag.Cutie:
    default: op
  cosmetics.tag.EventWinner:
    default: op
  cosmetics.tag.CapeCreator:
    default: op
  cosmetics.tag.Simp:
    default: op
  cosmetics.tag.Agro:
    default: op
  cosmetics.tag.Doofas:
    default: op
  cosmetics.tag.Clown:
    default: op
  cosmetics.tag.Duck:
    default: op
  cosmetics.tag.Pog:
    default: op
  cosmetics.tag.Potato:
    default: op
  cosmetics.tag.Discord:
    default: op
  cosmetics.tag.uwu:
    default: op
  cosmetics.tag.owo:
    default: op
  cosmetics.tag.Derp:
    default: op
  cosmetics.tag.Heart:
    default: op
  cosmetics.tag.BrokenHeart:
    default: op
  cosmetics.tag.Versai:
    default: op
  cosmetics.custom.tag:
    default: op

# Clan Tags
  
  cosmetics.tag.clan.Ace:
    default: op
  cosmetics.tag.clan.Aero:
    default: op
  cosmetics.tag.clan.Alpha:
    default: op
  cosmetics.tag.clan.Amense:
    default: op
  cosmetics.tag.clan.Arrow:
    default: op
  cosmetics.tag.clan.Carnage:
    default: op
  cosmetics.tag.clan.Derp:
    default: op
  cosmetics.tag.clan.Duck:
    default: op
  cosmetics.tag.clan.Evo:
    default: op
  cosmetics.tag.clan.Evolved:
    default: op
  cosmetics.tag.clan.Kratos:
    default: op
  cosmetics.tag.clan.Pixar:
    default: op
  cosmetics.tag.clan.Protocol:
    default: op
  cosmetics.tag.clan.Quantum:
    default: op
  cosmetics.tag.clan.Synergy:
    default: op
  cosmetics.tag.clan.Toxic:
    default: op
  cosmetics.tag.clan.Vape:
    default: op

  # Capes

  "cosmetics.cape.Versai":
    default: op
  "cosmetics.cape.Versai Dark":
    default: op
  "cosmetics.cape.Blue Claw":
    default: op
  "cosmetics.cape.Bunny":
    default: op
  "cosmetics.cape.Optifine Rainbow":
    default: op
  "cosmetics.cape.Playboy":
    default: op
  "cosmetics.cape.Red L":
    default: op
  "cosmetics.cape.Versai Easter":
    default: op

  # Particles ;(

  cosmetics.particles.follow.Critical:
    default: op
  cosmetics.particles.follow.Flame:
    default: op
  cosmetics.particles.follow.Splash:
    default: op
  cosmetics.particles.follow.Redstone:
    default: op
  cosmetics.particles.follow.Portal:
    default: op
  cosmetics.particles.follow.Spiral:
    default: op
  cosmetics.particles.follow.Glyph:
    default: op
  cosmetics.particles.follow.Heart:
    default: op
  cosmetics.particles.follow.Lava:
    default: op
  cosmetics.particles.follow.Ember:
    default: op
  cosmetics.particles.follow.Fire:
    default: op
  cosmetics.particles.follow.Smoke:
    default: op
  cosmetics.particles.follow.Explosion:
    default: op
  cosmetics.particles.follow.Rain:
    default: op
  cosmetics.particles.follow.Ink:
    default: op
  cosmetics.particles.follow.Darkness:
    default: op
  cosmetics.particles.follow.Cloud:
    default: op
  cosmetics.particles.follow.Star:
    default: op
  cosmetics.particles.follow.Diamond:
    default: op
  cosmetics.particles.follow.Emerald:
    default: op
  cosmetics.particles.follow.Lapis:
    default: op
  cosmetics.particles.follow.Gold:
    default: op

  cosmetics.particles.hit.Critical:
    default: op
  cosmetics.particles.hit.Flame:
    default: op
  cosmetics.particles.hit.Splash:
    default: op
  cosmetics.particles.hit.Redstone:
    default: op
  cosmetics.particles.hit.Portal:
    default: op
  cosmetics.particles.hit.Spiral:
    default: op
  cosmetics.particles.hit.Glyph:
    default: op
  cosmetics.particles.hit.Heart:
    default: op
  cosmetics.particles.hit.Lava:
    default: op
  cosmetics.particles.hit.Ember:
    default: op
  cosmetics.particles.hit.Fire:
    default: op
  cosmetics.particles.hit.Smoke:
    default: op
  cosmetics.particles.hit.Explosion:
    default: op
  cosmetics.particles.hit.Rain:
    default: op
  cosmetics.particles.hit.Ink:
    default: op
  cosmetics.particles.hit.Darkness:
    default: op
  cosmetics.particles.hit.Cloud:
    default: op
  cosmetics.particles.hit.Star:
    default: op
  cosmetics.particles.hit.Diamond:
    default: op
  cosmetics.particles.hit.Emerald:
    default: op
  cosmetics.particles.hit.Lapis:
    default: op
  cosmetics.particles.hit.Gold:
    default: op

...