---
name: Miscellaneous
version: 1.0.0
main: Versai\miscellaneous\Miscellaneous
api: 4.0.0
permissions:
  gamemode.spectate:
    default: op
  gamemode.creative:
    default: op
  gamemode.survival:
    default: op
  popcorn.use:
    default: op
  versai.full:
    default: op
  chat.protect:
    default: op
  chat_protect.bypass_cooldown:
    default: op
  chat_protect.bypass_message:
    default: op
  messages.join:
    default: true
  messages.quit:
    default: true
...