name: vStaff
main: Versai\vStaff\Main
version: 1.0.2
api: 4.0.0
load: POSTWORLD
author: Versai
permissions:
  staffhud.staffmode:
    default: op
    description: use /staff
  staffhud.staffmode.see:
    default: op
    description: See others in staff mode
  staffhud.staffmode.see_op:
    default: op
    description: See others in staff mode