---
# Usable variables "{reached_checkpoints} {left_checkpoints}"

progress-bar: "&bTime Elapsed:&3 {time}&2 Checkpoints&a {reached_checkpoints}&2/{left_checkpoints}"

parkour-start: "&eParkour started! Type &fQuit &eto leave and &fCheckpoint &eto teleport to the last checkpoint."
parkour-quit: "&cSuccessfully quit the parkour."
# Usable variables "{reached_checkpoints} {left_checkpoints}"
parkour-finish: "&eYou finished the parkour! &o&7[{time}]"

# Usable variables "{reached_checkpoints} {left_checkpoints}"
checkpoint-set: "&aCheckpoint Reached!&o&7 [{reached_checkpoints}/{left_checkpoints}]"
# Usable variables "{checkpoint}"
checkpoint-tp: "&fYou teleported to checkpoint&6 #{checkpoint}"
...
