---
name: RPGCore
author: "VersaiPE"
authors: ["TLS Gorilla", "Duo Incure", "minijaham", "GuildedThorn"]
description: "The core of the Versai RPG game mode"
version: 0.0.1
main: Versai\RPGCore\Main
api: 4.0.0
src-namespace-prefix: Versai\RPGCore
permissions:
  rpg:
    default: "false"
    description: "Main permission node for Versai RPGCore"
  rpg.command.stat:
    default: "op"
    description: "Allow permission to use the /stat command"
  rpg.command.stat.view:
    default: "true"
    description: "Allows permission to check a players stats"
  rpg.command.stat.manage:
    default: "op"
    description: "Allow permission to manage players stats"
  rpg.command.help:
    default: "true"
    description: "Permission to use the /smphelp command"
  rpg.command.npc:
    default: "op"
    description: "Allow permission to summon NPC's"
...
