---
name: Hotbar
main: ARTulloss\Hotbar\Main
api: 4.0.0
version: 2.0.5
author: ARTulloss
description: Hotbar Items!
permissions:
  hotbar.view:
    default: op
    description: Allows a user to run the hotbar command to view a list of all registered hotbars and the worlds they are assigned to
...
