<?php

declare(strict_types=1);

namespace Versai\RPG;

use pocketmine\plugin\PluginBase;
use pocketmine\utils\SingletonTrait;
use pocketmine\utils\TextFormat as TF;
use Versai\RPG\Commands\Settings;
use Versai\RPG\Libs\Discord\Webhook;
use Versai\RPG\Libs\Translate\Translator;
use Versai\RPG\Listeners\EventListener;

class Main extends PluginBase {

    use SingletonTrait;

    const PREFIX = "§7[§aR§2P§aG§7]";

    public $translator;

    /** @var Webhook  */
    private $webhook;

    public function onEnable(): void {
        # /langs/LOCALE.ini
        $this->translator = new Translator($this, "langs");
        $this->webhook = new Webhook($this->getConfig()->get("discord-webhook"));
        self::setInstance($this);

        $this->getServer()->getPluginManager()->registerEvents(new EventListener(), $this);
        $this->getServer()->getCommandMap()->register("versai", new Settings("settings", "change player settings"));
    }

    public function onDisable(): void {
        // TODO: Change the autogenerated stub
    }

    public function getTranslator(): Translator {
        return $this->translator;
    }

    public function getDiscordWebhook() {

    }
}