name: Duels
main: ARTulloss\Duels\Duels
api: 4.0.0
version: 1.2.8
author: ARTulloss
description: Duels!
loadbefore: [Hotbar]
depends: LibLoader
permissions:
  duels.reload:
    default: op
    description: Allows reloading the arenas
  duels.create_arena:
    default: op
    description: Allows creating an arena
  duels.remove_arena:
    default: op
    description: Allows removing an arena