database:
  host: 127.0.0.1
  schema: oneblock
  user: adam
  password: Uyauhi2UTG2cjtwZT2hF%fdf#5TsK


levels:
  0:
    podzol: 2
    mycelium: 2
    birch leaves: 5 # 9
    iron ore: 5 # 12
    oak log: 5 # 17
    dirt: 10 # 27
    andesite: 5 # 32
    dark oak log: 5 # 37
    oak leaves: 3 # 40
    diorite: 1 # 42
    coal ore: 8 # 45
    diamond ore: 2 # 46
    gold ore: 3 # 51
    grass: 10 # 61
    dark oak leaves: 4 # 65
    birch log: 5 # 70
    cobblestone: 7 # 77
    granite: 5 # 82
    coarse dirt: 2 # 84
    stone: 15 # 99
    emerald ore: 1 # 100
  1:
    cobblestone: 20
    dirt: 4
    stone: 22
    spruce leaves: 11
    stripped spruce log: 4
    ice: 2
    gold ore: 2
    lapis ore: 2
    spruce log: 11
    snow block: 22
  2:
    horn coral block: 2
    dirt: 6
    andesite: 9
    brain coral block: 2
    sandstone: 6
    red sand: 1
    dead horn coral block: 1
    wet sponge: 2
    bubble coral block: 2
    gravel: 7
    dead bubble coral block: 2
    prismarine: 9
    glowstone: 1
    tube coral block: 2
    sand: 19
    granite: 9
    stone: 9
    fire coral block: 2
    clay: 6
    sponge: 2
    dark prismarine: 2
    dead brain coral block: 1
    sea lantern: 2
  3:
    podzol: 4
    coal ore: 4
    mycelium: 4
    gravel: 2
    diamond ore: 1
    pumpkin: 2
    gold ore: 4
    grass block: 7
    jungle leaves: 18
    chest: 4
    jungle log: 18
    cobblestone: 4
    coarse dirt: 4
    stripped jungle log: 4
    dirt: 4
    stone: 18
    melon: 1
    emerald ore: 1
    lapis ore: 2
  4:
    coal ore: 7
    gravel: 5
    diamond ore: 1
    gold ore: 1
    grass block: 13
    chest: 7
    cobblestone: 9
    coarse dirt: 1
    oak log: 13
    dirt: 13
    stone: 1
    oak leaves: 13
    clay: 13
    emerald ore: 1
    lapis ore: 1
  5:
    coal ore: 6
    gravel: 6
    redstone ore: 3
    diamond ore: 3
    gold ore: 3
    iron ore: 6
    cobblestone: 8
    oak planks: 6
    sand: 6
    granite: 6
    dirt: 6
    stone: 11
    andesite: 6
    sandstone: 6
    emerald ore: 3
    brown mushroom block: 3
    lapis ore: 3
    diorite: 6
    red mushroom block: 3
    mossy cobblestone: 6
  6:
    sand: 53
    stone: 11
    red sandstone: 5
    sandstone: 26
    red sand: 5

whale:
  # The minimum amount of money that needs to be transferred to trigger a whale alert
  amount: 10000

# Starting price: 100
# Alot: 250000

# TODO: Find a work around for ore blocks because they are named the same thing in VanillaItems as they are in VanillaBlocks

sell:
  apple: 3
  baked potato: 5
  beetroot: 2
  beetroot seeds: 1
  beetroot soup: 6
  black dye: 4
  blaze powder: 15
  blaze rod: 9
  blue dye: 4
  bone: 2
  bone meal: 1
  bread: 10
  brick: 4
  brown dye: 4
  carrot: 1
  charcoal: 5
  clay: 2
  coal: 2
  cocoa beans: 3
  cooked chicken: 8
  cooked fish: 10
  cooked mutton: 8
  cooked porkchop: 8
  cooked rabbit: 12
  cooked salmon: 10
  cookie: 10
  cyan dye: 4
  diamond: 8
  dried kelp: 6
  egg: 2
  emerald: 30
  ender pearl: 10
  feather: 3
  flint: 4
  ghast tear: 16
  glistering melon: 6
  glowstone dust: 2
  golden carrot: 9
  gold ingot: 15
  gold nugget: 2
  gray dye: 4
  green dye: 4
  gunpowder: 4
  ink sac: 4
  iron ingot: 6
  iron nugget: 0.6
  lapis lazuli: 2
  leather: 3
  light blue dye: 4
  light gray dye: 4
  lime dye: 4
  magenta dye: 4
  melon: 1
  melon seeds: 1
  nether quartz: 4
  nether star: 100
  orange dye: 4
  paper: 6
  pink dye: 4
  potato: 1
  purple dye: 4
  raw beef: 4
  raw chicken: 6
  raw mutton: 5
  raw fish: 6
  raw porkchop: 5
  raw salmon: 5
  redstone dust: 1
  red dye: 4
  rotten flesh: 2
  slimeball: 5
  snowball: 1
  spider eye: 3
  steak: 14
  string: 3
  sugar: 5
  sweet berries: 3
  wheat: 1
  wheat seeds: 1

  # BLOCKS

  acacia leaves: 4
  acacia log: 3
  acacia planks: 1
  acacia sapling: 3
  acacia wood: 9
  andesite: 2
  anvil: 65
  bamboo: 1
  beacon: 90
  birch leaves: 4
  birch log: 3
  birch planks: 1
  birch sapling: 3
  birch wood: 9
  blue ice: 75
  bone block: 5
  #  bookshelf: 5
  #  bricks: 3
  brown mushroom: 4
  cactus: 2
  #  cake: 1
  block of coal: 22
  coal ore: 8
  cobblestone: 1
  dark oak leaves: 4
  dark oak log: 3
  dark oak planks: 1
  dark oak sapling: 3
  dark oak wood: 9
  dark prismarine: 9
  diamond ore: 12
  diamond block: 75
  diorite: 2
  dirt: 1
  emerald ore: 90
  end stone: 12
  end rod: 15
  #  end stone bricks: 1
  glass: 4
  #  glass pane: 1
  glowing obsidian: 18
  glowstone: 6
  gold block: 135
  gold ore: 14
  granite: 2
  grass: 1
  gravel: 2
  hay bale: 9
  ice: 1
  iron block: 54
  iron ore: 5
  jungle leaves: 4
  jungle log: 3
  jungle planks: 1
  jungle sapling: 3
  jungle wood: 9
  lapis lazuli block: 14
  lapis lazuli ore: 30
  magma: 10
  mycelium: 1
  netherrack: 4
  nether bricks: 6
  oak leaves: 4
  oak log: 3
  oak planks: 1
  oak sapling: 3
  oak wood: 9
  obsidian: 20
  packed ice: 10
  podzol: 1
  prismarine: 4
  prismarine bricks: 6
  pumpkin: 4
  purpur: 12
  purpur pillar: 9
  quartz: 5
  #  quartz pillar: 1
  redstone: 8
  redstone ore: 9
  red mushroom block: 4
  red nether bricks: 7
  #  red sand: 2
  #  red sandstone: 1
  sand: 2
  sandstone: 1
  slime: 1
  smooth quartz: 5
  #  smooth red sandstone: 1
  #  smooth sandstone: 1
  smooth stone: 2
  snow: 4
  soul sand: 4
  sponge: 3
  spruce leaves: 3
  spruce log: 4
  spruce planks: 1
  spruce sapling: 3
  spruce wood: 9
  stone: 3
  #  stone bricks: 1
  sugarcane: 2
  tnt: 7
  wool: 1


discord:
  webhooks:
    # THe webhook for bugs to be sent to
    bug:
      url: "https://discord.com/api/webhooks/1053413776579371078/ZRbCk2Y8XVaJF1XWWrUVGwIUGS70_RufrJkULHjZ3HQC_F7d6QfWKvR5E9cYEL2S9Jth"
    # Webhook to send an alert to when a Whale is detected
    whale:
      url: "https://discord.com/api/webhooks/1040050243548487700/i9zEDc-XF4AhD56lCpaBbUaYPllQXkkyQNz1QNLjNOjR84zvHvmClN40MOPlRFf0iptG"
      username: "Whale Alert"
      text_transfer: "{WHALE} sent ${AMOUNT} to {PLAYER}"
      text_sell: "{WHALE} sold items for a profit of ${AMOUNT} \n {ITEMS}"
      color: "FFFFFF"