--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JustSxm/SamCrates
build-by-default: true
branches:
  - master
projects:
  VCrates:
    path: ""
    libs:
      - src: poggit\libasyncql\libasyncql
        version: 3.3.1
      - src: musqsit\invmenu\invmenu
        version: 4.1.0
      - src: dktapps\pmforms\pmforms
        version: 1.0.0
...
