import:
 source: ./tests/travis/setup-php.yml

script:
 - composer install --prefer-dist
 - ./vendor/bin/phpstan analyze --no-progress --memory-limit=2G
 - ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit
 - composer install --no-dev --prefer-dist
 - ./tests/travis.sh -t4

cache:
  - $HOME/.composer/cache/files
  - $HOME/.composer/cache/vcs

notifications:
 email:
  recipients:
   - team@pmmp.io
  on_success: change
  on_failure: always
