---
servers:
  practice:
    address: versai.pro
    port: 9000
    img: textures/items/potion_bottle_splash_heal
  build:
    address: eu.versai.pro
    port: 9000
    img: textures/blocks/sandstone_normal
  vanilla survival:
    address: survival.versai.pro
    port: 19160
    img: textures/blocks/grass_block
  modded survival:
    address: survival.versai.pro
    port: 19170
    img: textures/blocks/diamond_ore
...