---
name: Sumo
version: 0.0.1
main: Martin\Sumo\Main
api: 3.0.0
permissions:
  sumo.games:
    default: op
    description: Create and manage games
  sumo.creator:
    default: op
    description: Create sumo tournaments
...
