name: vLobby
main: vlobby\Main
api: 3.0.0
version: 1.0.2
authors: ["diverse", "T14Raptor"]

permissions:
  vlobby:
    default: false
    children:
      vlobby.bypass:
        default: op
      vlobby.fly:
        default: op