---
Defaults:
  Knockback: 0.4
  Hit-Cooldown: 10
  Item-Pickup: true
  Hunger-Loss: true
  Fall-Damage: true
  Breakable: true
  Placeable: true
  Block-Decay: false
  Build-Limit: 256
  Allowed-Block-List: []
...
