database:
  host: "localhost"
  user: "root"
  password: "root"
  database: "versaiskyblock"
island:
  base: "SkyblockBase"

enchants:
  # Will attack multiple mobs in a 3 block radius of the mob you hit
  sweep:

  # Will increase the chance of getting a key