---

# Messages

join-message: "§8[§a+§8] §a{player}"
leave-message: "§8[§c-§8] §8{player}"
kill-messages:
- "{player} was killed by {killer} §c[{health}]"
- "{player} was quickied by {killer} §c[{health}]"
- "{player} was L'd by {killer} §c[{health}]"
- "{player} was dropped by {killer} §c[{health}]"
- "{player} was clapped by {killer} §c[{health}]"
- "{player} was dropped by {killer} §c[{health}]"
- "{player} was oofed killed by {killer} §c[{health}]"
- "{player} got railed by {killer} §c[{health}]"

death-contact: "§c{player} was pricked to death!"
death-projectile: "§c{player} shot by {killer}"
death-suffocation: "§c{player} forgot to breath!"
death-fall: "§c{player} slipped because of {killer}"
death-fire: "§c{player} burned to death!"
death-lava: "§c{player} melted!"
death-drown: "§c{player} forgot to breath!"
death-explosion: "§c{player} went out with a bang!"
death-void: "§c{player} fell into the void!"
death-suicide: "§c{player} committed dead! D="
death-magic: "§c{player} was killed by a spell!"
death-starvation: "§c{player} forgot to eat!"

# Changing stuff

every: 60 # seconds

broadcasts:
- "§9[Versai] Thanks for playing, {player}"
- "§9[Versai] Check out our shop where you can get cool stuff!"
- "§9[Versai] Follow us on Twitter @VersaiPE"
- "§9[Versai] More features are coming soon!"
- "§9[Versai] Enjoying Versai, make sure to vote so more people can discover us!"
- "§9[Versai] Join our official discord at discord.versai.pro!"
- "§9[Versai] There are {online} / {max} players online!"

motd:
- §9versai.pro §6«
- §9Free to play §6«
- §9Cosmetics! §6«
- §9Free for all! §6«

Cooldown: 0.5
Enable-Cooldown: true
Enable-Block-Repeat-Messages: false

