---
name: Parkour
main: Fadhel\Parkour\Main
version: 2.0.0-ALPHA
api: 4.0.0
authors: ["Fadhel", "ARTulloss", "lovediverse"]
description: A parkour plugin for Versai
permissions:
  parkour.create:
    default: op
  parkour.end:
    default: op
...
