name: vTempRanks
main: Versai\vTempRanks\Main
api: 4.0.0
version: 1.0.0
author: Versai
description: Temporary Ranks!
src-namespace-prefix: Versai\vTempRanks
depend:
  - vHierarchy
permissions:
  temprank.command:
    default: op
    description: Temp Rank Command!