<?php

namespace impl\sexypots;

use pocketmine\entity\Effect;
use pocketmine\entity\EffectInstance;
use pocketmine\entity\Entity;
use pocketmine\level\Level;
use pocketmine\nbt\tag\CompoundTag;

class SplashPotion extends \pocketmine\entity\projectile\SplashPotion {

	public const NETWORK_ID = self::SPLASH_POTION;

	public function __construct(Level $level, CompoundTag $nbt, ?Entity $shootingEntity = null) {
		parent::__construct($level, $nbt, $shootingEntity);
		$this->width += 0.35;
		$this->height += 0.25;
	}

	public function entityBaseTick(int $tickDiff = 1): bool {
		$this->motion->y -= 0.12;
		$this->motion->y *= 0.9800000190734863;
		$this->motion->x *= 0.91;
		$this->motion->z *= 0.91;
		return parent::entityBaseTick($tickDiff); // TODO: Change the autogenerated stub
	}

	public function getPotionEffects(): array {
		return [new EffectInstance(Effect::getEffect(Effect::INSTANT_HEALTH), null, 2)];
	}

	protected function applyGravity(): void {
	}

	protected function tryChangeMovement(): void {
	}

}